name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        run: |
          docker login -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }} ${{ secrets.AZURE_URL }}

      - name: Build and push to azure registry
        run: |
          cd src/Student.Email.Assistant.Backend
          ls -l
          docker build -t aiscrummasterprod.azurecr.io/student-email-assistant:latest .
          docker push aiscrummasterprod.azurecr.io/student-email-assistant:latest
